name: KoxiakoweGildie
version: 1.0
main: pl.koxiakowe.gildie.KoxiakoweGildie
api-version: 1.16
depend: [Vault, PlaceholderAPI]
authors: [Koxiak]
description: Plugin na Gildie
commands:
  gildia:
    description: Główna komenda do zarządzania gildiami
    usage: /gildia
    aliases: [g]
permissions:
  gildie.admin:
    description: Uprawnienia administratora gildii
    default: op
  gildie.zarzadzanie:
    description: Uprawnienia do zarządzania gildią
    default: true 